---
name: 'test-action'
on: 
  # [push, pull_request]
  workflow_dispatch:
jobs:
  dirtree:
    runs-on: ubuntu-latest
    name: 'Get and save dirtree to `README.md`'
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          repository: qte77/dirtree-readme-action
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Call action
        uses: ./
...
